Renamed /doc files to kebab-case
roboticslab-uc3m/yarp-devices pull request #142
Opened 2017-11-21 14:01 UTC by rsantos88

Renamed /doc files to kebab-case

2017-11-21 14:05 UTC, PeterBowman requested changes
Please fix links too on:

* yarp-devices-install.md
* yarp-devices-install-on-debian-6.md

2017-11-23 16:12 UTC, rsantos88 commented
thanks @PeterBowman!
I think it's right now.

2017-11-23 16:13 UTC, PeterBowman approved these changes

2017-11-23 19:18 UTC, merged

2017-11-23 19:18 UTC, jgvictores reviewed
Good!