Provide encoderPulses config option
roboticslab-uc3m/yarp-devices pull request #144
Opened 2017-11-27 16:02 UTC by rsantos88

Provide encoderPulses config option

2017-11-27 16:20 UTC, PeterBowman requested changes

2017-11-27 16:20 UTC, PeterBowman commented on libraries/YarpPlugins/TechnosoftIpos/IPositionControl2RawImpl.cpp
> +    double val = encoderPulses / 360; // encoderPulses: value encompasses the pulses-per-slot factor (usually 4) and number of total slots of the encoder (currently: 4 * 1024).
`encoderPulses / 360.0` (note the decimal point) so that the result is a double. See https://stackoverflow.com/q/7571326. Same a few lines below.

2017-11-27 16:20 UTC, PeterBowman commented on libraries/YarpPlugins/CanBusControlboard/DeviceDriverImpl.cpp
> +    yarp::os::Bottle encoderPulses = config.findGroup("encoderPulses").tail();  //-- e.g. 4096 (4 * 1024)
`encoderPulsess` (note the double 's'). Compare with line 78 on this same file (TechnosoftIpos reads a `encoderPulses` - one 's').

2017-11-27 16:20 UTC, PeterBowman commented on libraries/YarpPlugins/TechnosoftIpos/DeviceDriverImpl.cpp
> +    this->encoderPulses = config.check("encoderPulses",0,"encoderPulses").asDouble();
`.asInt()`

2017-12-01 12:38 UTC, PeterBowman reviewed
@rsantos88 could you provide this same set of `encoderPulsess` defaults (4096) at `share/oneCanBusOneWrapper/` (.ini files)?

2017-12-04 10:12 UTC, jgvictores commented
Could we update https://github.com/roboticslab-uc3m/yarp-devices/tree/develop/firmware/CuiAbsolute to match these numbers?

2017-12-04 10:22 UTC, rsantos88 commented
for example, do you want to change [this](https://github.com/roboticslab-uc3m/yarp-devices/blob/develop/firmware/CuiAbsolute/Pic_source/main.c#L86) line to something like this?:
```c
/***** Variables configurables (CAN_ID & SEND_DELAY) *******************************************************/

// CAN ID (Ver correspondecia en http://robots.uc3m.es/index.php/CuiAbsolute_Documentation)
unsigned long canId = 498; //508 (codo 124) 492 (pierna izquierda 108)

// ENCODER PULSES
double encoderPulses = 4096;

/* SEND DELAY (Valor que utilizará Delay10TCYx en el envío. Valor recomendado de 1 a 100)
 * El byte 3 (data[2]) que recibirá el PIC (valor comprendido entre [0-255]) se multiplicará por el tiempo que
 * tarde en ejecutar el delay marcado por la función Delay10TCYx(sendDelay)
 * A tener en cuenta:
	- La velocidad de ejecución de cada ciclo de instrucción son 0.8 microsegundos
        - Delay10TCYx(i) -> 10.Tcy.i genera una demora de 10 ciclos de instrucciones * i . Por tanto Delay10TCYc(1) equivale a 8 microsegundos (10 ciclos de reloj) */
BYTE sendDelay = 1; //Default: 1 
/***********************************************************************************************************/

// -- Inicialización de variables para el envío
int aux, message[2];
int i=0;
double degrees;
double div = encoderPulses/360.0;
```

2017-12-04 10:25 UTC, jgvictores commented
Yes

2017-12-04 13:31 UTC, PeterBowman requested changes
Not all harcoded occurrences of 11.38 (and its multiples) have been replaced, yet. Please run the following command at `libraries/YarpPlugins/TechnosoftIpos`:

`grep -rnIP '11\.?38'`

2017-12-04 15:53 UTC, PeterBowman approved these changes

2017-12-04 15:54 UTC, merged