Jr3 improvement: new  calibrateSensor and calibrateChannel functions
roboticslab-uc3m/yarp-devices pull request #199
Opened 2019-01-14 11:11 UTC by rsantos88

* implemented calibrateSensor and calibrateChannel functions 
* created new example to test the new calibrating functions

2019-01-14 15:02 UTC, jgvictores commented
The example is in fact local, so:
- `exampleRemoteJr3-2` -> `exampleJr3` (following the naming conventions of the other examples, that put nothing if local)
- L29 and L30 can dissapear: https://github.com/roboticslab-uc3m/yarp-devices/blob/b5c6b3db6244f305f0098a7f0ecef46675ead1f4/examples/cpp/exampleRemoteJr3-2/exampleRemoteJr3-2.cpp#L29-L30

2019-01-15 23:11 UTC, PeterBowman requested changes

2019-01-15 23:11 UTC, PeterBowman commented on libraries/YarpPlugins/Jr3/IAnalogSensorImpl.cpp
> +        return yarp::dev::IAnalogSensor::AS_OK;
Return `yarp::dev::IAnalogSensor::AS_ERROR` otherwise.

2019-01-15 23:11 UTC, PeterBowman commented on libraries/YarpPlugins/Jr3/IAnalogSensorImpl.cpp
> +            ok = false;
`ok = -1;` per the following `if` clause.

2019-01-15 23:11 UTC, PeterBowman commented on libraries/YarpPlugins/Jr3/IAnalogSensorImpl.cpp
> +        return yarp::dev::IAnalogSensor::AS_OK;
Return `yarp::dev::IAnalogSensor::AS_ERROR` otherwise.

2019-01-28 14:39 UTC, jgvictores commented
@rsantos88 Is this WIP or ready for review/merge?

2019-01-28 14:58 UTC, rsantos88 commented
Yes! I've fixed the errors of the notes. Review it and if you don't see anything stranger, merge it :)

2019-01-28 15:09 UTC, PeterBowman commented
Could you remove the autogenerated Qt file from the commit history (git rebase -i)?

2019-01-29 11:48 UTC, rsantos88 commented
Ok @PeterBowman. I've removed the file from the [git repository history](https://myopswork.com/how-remove-files-completely-from-git-repository-history-47ed3e0c4c35) and from commit history using `git rebase -i`. Please, review it

2019-01-29 15:37 UTC, PeterBowman approved these changes

2019-01-29 15:49 UTC, merged